theme: jekyll-theme-cayman

title: [Fran Simó]
description: [“Art is plastic thought. A swing between ideas and aesthetics.”]

# About/contact
author:
  name: Fran Simó
  url: https://fransimo.info/
  location: "Palma, Spain"
